### ISSUE TITLE
#E int vs float

### ISSUE THREAD

**Issue by JPHammonds** [prjemian/spec2nexus#117]
I have been going back and forth with the creator of a "SPEC" file.  (created by a program other than spec) Finally got them to pass the initial "is it a spec file test" except that they fed a float # of seconds in the #E field.  Is it possible to deal with this since the spec is unclear on this?

**Comment by prjemian** [comment]
Seems reasonable that it could be a float.  There is no standard, only customary.

**Comment by JPHammonds** [comment]
Thanks,

No huge rush.

**Comment by prjemian** [comment]
milestone: [2017-12-01](https://github.com/prjemian/spec2nexus/milestone/8)

**Comment by prjemian** [comment]
@JPHammonds: BUT, there is a downside to reading #E as a float.  Potential loss of display precision.

Current algorithm now is to examine the #E line for a "." and read as float, otherwise as int.  Since there is no *reasonable* use of the sub-second precision gained by reading as a float, would it be satisfactory to split the string at the decimal point and only parse the integer part of the time?  Since the file is not written by SPEC, do they care?  Is there some other process that is sensitive to how *spec2nexus* reads this value?
