### ISSUE TITLE
no data group in NeXus file if no data

### ISSUE THREAD

**Issue by prjemian** [prjemian/spec2nexus#45]
If there are no data lines in a spec data scan, then no NXdata group will be written, even though the parent NXentry calls for a group named "data".

This violates the NeXus requirement that every NXentry must have at least one NXdata group with plottable data.

**Comment by prjemian** [comment]
In such cases, synthesize a trivial data:NXdata for the default plot and leave a note there what was done.

**Comment by rayosborn** [comment]
If this is really a requirement, then I think this should be changed at the next NIAC to "strongly encouraged." I'll raise it at the next telco for comments.

**Comment by prjemian** [comment]
There is no question that it is a requirement.  The requirement implements the motivation for "simple plotting."

* http://download.nexusformat.org/doc/html/motivations.html?highlight=motivation
* http://download.nexusformat.org/doc/html/introduction.html#important-classes

**Comment by rayosborn** [comment]
I understand the motivation. I just think it's a mistake to mandate something when there are valid reasons for not being able to conform. This is a case in point. It would be silly not to have an entry when the SPEC file adds a scan number, partly for consistency and partly because there are other metadata to store, but I also think it doesn't make sense to put in dummy data. I don't object to your solution; I just think we should relax the requirement, because it's the kind of rigidity that causes some people to object.
